version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: goticket_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goticket
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - goticket_net

  redis:
    image: redis:7
    container_name: goticket_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - goticket_net

  kafka:
    image: apache/kafka:3.7.0
    container_name: goticket_kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft settings
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - goticket_net

volumes:
  mysql_data:
  redis_data:

networks:
  goticket_net:
    driver: bridge
